image:
  name: dock.matrix.msu.edu/matrix/triton-job-runner:latest


stages:
  - build
  - deploy

variables:
  ANSIBLE_PYTHON_INTERPRETER: '/opt/local/bin/python3'
  ANSIBLE_HOST_KEY_CHECKING: 'False'

build:
  stage: build
  script:
   - apk add php7-tokenizer
   - php -v
   - php -m
   - cd src/source/; composer install --no-dev ; cd ..
   - composer install --no-dev
   - npm install
   - cp config.dist.php config.php
   - sed -i 's#ENVIRONMENTBASEPATH#/builds/matrix/enslaved/src/build_local#' config.php
   - cp source/config.dist.php source/config.php
   - sed -i 's#ENVIRONMENTBASEURL#https://enslaved.dev.matrix.msu.edu/#' source/config.php
   - sed -i 's#ENVIRONMENTBASEPATH#/builds/matrix/enslaved/src/build_local/#' source/config.php
   - sed -i "s#SECRETTOKENGOESHERE#$KORA_TOKEN#" source/config.php
   - cp source/.dist.htaccess source/.htaccess
   - cp source/database-config.dist.php source/database-config.php
   - npm run dev ; cd ..
   - cp -r src/build_local/ public/
  artifacts:
    expire_in: 1 day
    paths:
      - public/

deploy-staging:
  stage: deploy
  script:
   - mkdir -p ~/.ssh || true
   - chmod 700 ~/.ssh
   - eval $(ssh-agent -s)
   - echo "$TRITON_KEY" | tr -d '\r' | ssh-add -
   - echo "Key loaded"
   - function cleanup() { kill $SSH_AGENT_PID;  }
   - trap cleanup EXIT
   - sed -i 's#/builds/matrix/enslaved/src/build_local/#/opt/local/share/httpd/htdocs/#' public/config.php
   - sed -i 's#ENVIRONMENTBASEPATH#/#' public/.htaccess
   - ansible-playbook ansible/deploy-website.yml
  artifacts:
    expire_in: 1 day
    paths:
      - public/
  environment:
    name: staging
    url: https://enslaved.dev.matrix.msu.edu/
  variables:
    ANSIBLE_INVENTORY: 'ansible/staging.hosts'
