<?php
const occupation=["Agriculture, Forestry, and/or Livestock" => "Q87",
"Domestic Service" => "Q88",
"Police and/or Military" => "Q90",
"Industry" => "Q91",
"Maritime" => "Q92",
"Marketing and Trading" => "Q93",
"Crafts and Trades" => "Q94",
"Healthcare and Medical" => "Q95",
"Religious" => "Q96",
"Legal" => "Q97",
"Teaching" => "Q98",
"Arts and Entertainment" => "Q99",
"Management" => "Q100",
"Other Occupation" => "Q101",
"Banking and Commerce" => "Q102",
"Fishing, Hunting, and/or Gathering" => "Q104",
"Writing and/or Publishing" => "Q105",
"Landowning" => "Q106",
"Slave Trade" => "Q107",
"Government" => "Q115",
"Crime" => "Q116",
"Sex Work" => "Q121"];
?>
