<?php
//Q numbers are all wrong
const eventTypes=[
    'Baptism or Naming Ceremony' => 'Q125',
    'Birth' => 'Q126',
    'Death' => 'Q146',
    'Disappearance' => 'Q147',
    'Education' => 'Q148',
    'Emancipation or Manumission' => 'Q149',
    'Employment, Apprenticeship, or Indenture' => 'Q150',
    'Legal Proceedings' => 'Q151',
    'Marriage' => 'Q153',
    'Membership' => 'Q154',
    'Military Service' => 'Q155',
    'Narrative' => 'Q156',
    'Rebellion' => 'Q157',
    'Registry' => 'Q159',
    'Relocation' => 'Q160',
    'Residence' => 'Q161',
    'Sale' => 'Q164',
    'Self-Purchase' => 'Q165',
    'Trade' => 'Q166',
    'Voyage' => 'Q250',
    'Emancipation or Manumission' => 'Q281',
    'Embarkation' => 'Q10087',
    'Disembarkation' => 'Q10088'
];

const qeventTypes = [
  "Q125" => "Baptism or Naming Ceremony",
  "Q126" => "Birth",
  "Q146" => "Death",
  "Q147" => "Disappearance",
  "Q148" => "Education",
  "Q149" => "Emancipation or Manumission",
  "Q150" => "Employment, Apprenticeship, or Indenture",
  "Q151" => "Legal Proceedings",
  "Q153" => "Marriage",
  "Q154" => "Membership",
  "Q155" => "Military Service",
  "Q156" => "Narrative",
  "Q157" => "Rebellion",
  "Q159" => "Registry",
  "Q160" => "Relocation",
  "Q161" => "Residence",
  "Q164" => "Sale",
  "Q165" => "Self-Purchase",
  "Q166" => "Trade",
  "Q250" => "Voyage",
  "Q281" => "Emancipation or Manumission",
  "Q10087" => "Embarkation",
  "Q10088" => "Disembarkation"
];
