<?php
const occupation = [
    "Agriculture, Forestry, and/or Livestock" => "Q87",
    "Arts and Entertainment" => "Q99",
    "Crafts and Trades" => "Q94",
    "Domestic Service" => "Q88",
    "Fishing, Hunting, and/or Gathering" => "Q104",
    "Government" => "Q115",
    "Healthcare and Medical" => "Q95",
    "Industry" => "Q91",
    "Landowning" => "Q106",
    "Legal" => "Q97",
    "Manual Labor" => "Q102",
    "Maritime" => "Q92",
    "Marketing and Trading" => "Q93",
    "Military and Militia" => "Q447",
    "Other Occupation" => "Q101",
    "Police and/or Military" => "Q90",
    "Religious" => "Q96",
    "Slave Trade" => "Q107",
    "Teaching" => "Q98",
    "Transportation" => "Q116",
    "Writing and/or Publishing" => "Q105"
];

const qoccupation = [
    "Q87" => "Agriculture, Forestry, and/or Livestock",
    "Q99" => "Arts and Entertainment",
    "Q94" => "Crafts and Trades",
    "Q88" => "Domestic Service",
    "Q104" => "Fishing, Hunting, and/or Gathering",
    "Q115" => "Government",
    "Q95" => "Healthcare and Medical",
    "Q91" => "Industry",
    "Q106" => "Landowning",
    "Q97" => "Legal",
    "Q102" => "Manual Labor",
    "Q92" => "Maritime",
    "Q93" => "Marketing and Trading",
    "Q447" => "Military and Militia",
    "Q101" => "Other Occupation",
    "Q90" => "Police and/or Military",
    "Q96" => "Religious",
    "Q107" => "Slave Trade",
    "Q98" => "Teaching",
    "Q116" => "Transportation",
    "Q105" => "Writing and/or Publishing"
];    
