<?php
const places =
['New Orleans' => 'Q28',
    'Louisiana' => 'Q30',
    'United States of America' => 'Q33',
    'Office of the Mayor of New Orleans' => 'Q38',
    'North America' => 'Q51',
    'Continent' => 'Q52',
    'West Central Africa FN Region' => 'Q144',
    'Baltimore' => 'Q268',
    'Natchitoches' => 'Q286',
    'Montevideo' => 'Q294',
    'Iglesia del Santo Cristo del Buen Viaje' => 'Q436',
    'Havana' => 'Q437',
    'Cuba' => 'Q438',
    'Saint Thomas' => 'Q488',
    'Saint-Domingue' => 'Q516',
    'Iglesia de Jesús, María y José' => 'Q526',
    'Rio de Janeiro' => 'Q561',
    'Trelawney' => 'Q572',
    'Lagos' => 'Q589',
    'Matanzas' => 'Q590',
    'Havannah' => 'Q591',
    'Sherbro' => 'Q596',
    'St. Helena Island FN Region' => 'Q163'
];

const qPlaces =
['Q28' => 'New Orleans',
    'Q30' => 'Louisiana',
    'Q33' => 'United States of America',
    'Q38' => 'Office of the Mayor of New Orleans',
    'Q51' => 'North America',
    'Q52' => 'Continent',
    'Q144' => 'West Central Africa FN Region',
    'Q163' => 'St. Helena Island FN Region',
    'Q268' => 'Baltimore',
    'Q286' => 'Natchitoches',
    'Q294' => 'Montevideo',
    'Q436' => 'Iglesia del Santo Cristo del Buen Viaje',
    'Q437' => 'Havana',
    'Q438' => 'Cuba',
    'Q488' => 'Saint Thomas',
    'Q516' => 'Saint-Domingue',
    'Q526' => 'Iglesia de Jesús, María y José',
    'Q561' => 'Rio de Janeiro',
    'Q572' => 'Trelawney',
    'Q589' => 'Lagos',
    'Q590' => 'Matanzas',
    'Q591' => 'Havannah',
    'Q596' => 'Sherbro'
];
?>
